include:
  - project: 'omni/devops-team/devops/ci-templates'
    ref: $PIPELINE_TEMPLATE_REF
    file: 'generic.yml'

variables:
  TARGET: target
  TAG: $CI_COMMIT_SHORT_SHA

stages:
  - prepare
  - build

prepare:
  tags:
    - vm
  stage: prepare
  extends:
    - .prepare_configs
  only:
    - master

build:
  tags:
    - vm
  stage: build
  variables:
    DESTINATION: https://art.x5.ru:443/artifactory/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  extends:
    - .build
  only:
    - master